### ISSUE TITLE
vim-surround not working with custom objects

### ISSUE THREAD

**Issue by thalesmello** [kana/vim-textobj-user#59]
Given:

```vim
Plug 'tpope/vim-surround'
Plug 'kana/vim-textobj-user'
Plug 'kana/vim-textobj-function'
Plug 'thinca/vim-textobj-function-javascript'
```

And `file.js`:

```js
function foo () {
  throw new Error('what?')
}
```

If I type `ysaf` to surround around the function, I get:

```

tore-marks)unction foo () {
  throw new Error('what?')
}
```

Apparently, it was caused by 7e67965

8e885f9 doesn't show this behavior

**Comment by kana** [comment]
Thank you for the report. I'll look into the problem later.

**Comment by kana** [comment]
I've looked into the problem.  It is caused by use of `getchar()` in vim-surround.  For example, if a user types `ysiw(`, this `(` is consumed by `getchar()`.  But if a user types `ysaf`, this will be processed by Vim as follows:

1. `ysaf` (what a user typed)
2. `af` (`ys` was evaluated. vim-surround did preparation for further actions.)
3. `<SNR>123_(save-marks):<C-u>call ...<CR><SNR>123_(restore-marks)` (`af` was remapped by vim-textobj-user to this magic stuff.)
4. `<SNR>123_(restore-marks)` (`<SNR>123_(save-marks):<C-u>call ...<CR>` was evaluated.)
5. `123_(restore-marks)` (vim-surround called `getchar()` and `<SNR>` was consumed.  Since `<SNR>` is not a valid surrounding character, vim-surround did nothing for `ysaf`.)
6. `(restore-marks)` (`123_` was evaluated.  This is a valid Vim command. The cursor was moved to somewhere.)
7. `restore-marks)` (The same can be said for `(`.)
8. `store-marks)` (The character under the cursor was replaced with `e`.)
9. `tore-marks)` (The character under the cursor was deleted, then Vim shifted to Insert mode.)

**Comment by kana** [comment]
Hmm… it's painful that vim-surround doesn't work with custom text objects.  The problem which was resolved by https://github.com/kana/vim-textobj-user/pull/55 is also painful, but not so much.  I'll revert the PR and try finding other solutions.

**Comment by radostyle** [comment]
Hi kana,
I updated to the latest 0.7.5 e231b65   and I'm still not able to surround with line.  I thought my version of a line textobj was not up to snuff so I found your version vim-textobj-line  and still ysil" or ysil'  does not work for me.

**Comment by pkrumins** [comment]
Can you try if it works with vim-sandwich (https://github.com/machakann/vim-sandwich). I keep hearing that this plugin is a better surround.vim but I haven't tried it myself yet.
